<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Globales_monolitico" Id="{cdd81dfd-df97-4b3b-b674-a3aed90a8356}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Globales_monolitico
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>