<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{19798f55-9da0-48b7-a2d0-4bd977cab0f2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbFMS205 : FB_FMS205;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbFMS205();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="11" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>