<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Module_Base" Id="{3a301875-b2bb-427d-a6fa-5afb38800442}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Module_Base
VAR_INPUT
	IC		: BOOL;
	Execute	: BOOL;
	Ack		: BOOL;
END_VAR

VAR_OUTPUT
	Ready		: BOOL;
	Failure		: BOOL;
	Done		: BOOL;
END_VAR

VAR
	tm		: S_Timeouts;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>