<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_DetectorCapacitivo" Id="{51b32ed3-45d8-4130-8ade-74f05fee5c33}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DetectorCapacitivo EXTENDS FB_Module
(*
ESTACIONES DE DETECCIÓN DE MATERIAL - Manual de usuario #32/28

La detección de las tapas realizadas en nylon, ha de llevarse a cabo por tanto 
a través de otro sensor. Para ello se ha dispuesto un detector capacitivo, 
que a diferencia del anterior proporciona una señal al PLC cuando se sitúa 
en su rango de detección una pieza de cualquier material 

*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Falta el hardware de este módulo]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>