<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="L1_ModuleBase" Id="{cba3fcf8-6c8d-4174-8dda-f766b8b369f3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK L1_ModuleBase

VAR_INPUT
	dr		: REFERENCE TO L1_Director;
	ID		: BYTE; 		// identificador de la unidad funcional (el módulo)
	Name	: STRING;		// Nombre del módulo (para erroers)
	Execute	: BOOL;
	Ack		: BOOL;
END_VAR

VAR_OUTPUT
	IC			: BOOL;
	Ready		: BOOL;
	Failure		: BOOL;
	FailName 	: STRING;
	Done		: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>