<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_FMS205_UI" Id="{1f1a7947-eda9-4e77-81cf-c2d20a4dbc79}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_FMS205_UI
VAR_INPUT
    angulo: REAL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
    act_K_1		: BOOL;
    act_FM		: BOOL;
    act_AS		: BOOL;
    act_LM		: BOOL;
    act_DPO		: BOOL;
    act_LA		: BOOL;
    act_A_1		: BOOL;
    act_B_1		: BOOL;
    act_C_1		: BOOL;
    act_L_1		: BOOL;
    act_F_0		: BOOL;
    act_F_1		: BOOL;
    act_G_1		: BOOL;
    act_V_1		: BOOL;
    act_H_1		: BOOL;
    act_I_1		: BOOL;
    act_J_1		: BOOL;
    act_D_1		: BOOL;
    act_E_1		: BOOL;
    act_RUN		: BOOL;
    act_Avanza		: BOOL;
    act_REV		: BOOL;
    act_Retroc		: BOOL;
    act_R_1		: BOOL;
    act_S_1		: BOOL;
    sen_PE		: BOOL;
    sen_POC		: BOOL;
    sen_PM		: BOOL;
    sen_SM		: BOOL;
    sen_k1		: BOOL;
    sen_a0		: BOOL;
    sen_a1		: BOOL;
    sen_b0		: BOOL;
    sen_b1		: BOOL;
    sen_dh		: BOOL;
    sen_df		: BOOL;
    sen_di		: BOOL;
    sen_f0		: BOOL;
    sen_f1		: BOOL;
    sen_g0		: BOOL;
    sen_v1		: BOOL;
    sen_h0		: BOOL;
    sen_h1		: BOOL;
    sen_i0		: BOOL;
    sen_i1		: BOOL;
    sen_d0		: BOOL;
    sen_pp		: BOOL;
    sen_cp0		: BOOL;
    sen_cp1		: BOOL;
    sen_cp2		: BOOL;
    fun_ABIn		: BOOL;
    fun_AAIn		: BOOL;
    fun_BBIn		: BOOL;
    fun_BAIn		: BOOL;
    fun_NBIn		: BOOL;
    fun_NAIn		: BOOL;
    fun_Llenar		: BOOL;
    fun_Vaciar		: BOOL;
    fun_Alimentar		: BOOL;
    fun_Girar		: BOOL;
    fun_Situar		: BOOL;
    fun_Altura		: BOOL;
    fun_Color		: BOOL;
    fun_Material		: BOOL;
    fun_Cargar		: BOOL;
    fun_Rechazar		: BOOL;
    fun_Descargar		: BOOL;
    fun_Transferir		: BOOL;
    bot_Planta		: BOOL;
    bot_Empezar		: BOOL;
    bot_Emerg		: BOOL;
    bot_Pausar		: BOOL;
    bot_Reset		: BOOL;
    bot_Funcion		: BOOL;
    bot_Ejecutar		: BOOL;
    bot_Continuar		: BOOL;



END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>